Us012 add new role to existing job family and band
AlexMcC02/TeamTwo-BackEnd pull request #14
Opened 2023-08-01 10:44 UTC by gibpaul

2023-08-01 11:22 UTC, gibpaul commented
@ccurran01

2023-08-02 09:52 UTC, ConnMeehan approved these changes

2023-08-02 09:57 UTC, philipwilson5 approved these changes

2023-08-02 13:19 UTC, shaunganley requested changes
great start, some small comments and needs integration tests

2023-08-02 13:19 UTC, shaunganley commented on src/main/java/org/kainos/ea/cli/BandRequest.java
> +public class BandRequest {
looks like this isn't needed?

2023-08-02 13:19 UTC, shaunganley commented on src/main/java/org/kainos/ea/service/CapabilityService.java
> +        }
can you merge these 2 catch blocks into 1 catch block

2023-08-02 13:19 UTC, shaunganley commented on src/main/java/org/kainos/ea/validator/BandValidator.java
> +public class BandValidator {
not sure this is needed?

2023-08-02 13:19 UTC, shaunganley commented on src/main/java/org/kainos/ea/validator/JobRoleValidator.java
> +public class JobRoleValidator {
can you also check if the capability ID and band ID exist in the database

2023-08-02 13:19 UTC, shaunganley commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
> +    @Test
you're not mocking out your validator anywhere in here. need a unit test for what happens when validation fails

2023-08-03 14:39 UTC, shaunganley approved these changes

2023-08-03 14:44 UTC, merged