us001-view-job-roles
AlexMcC02/TeamTwo-BackEnd pull request #3
Opened 2023-07-19 12:38 UTC by AlexMcC02

Required functionality added with passing integration tests and tests of the service class.

2023-07-19 14:26 UTC, shaunganley requested changes
good start. let me know if you have any questions about my comments

2023-07-19 14:26 UTC, shaunganley commented on pom.xml
>      <modelVersion>4.0.0</modelVersion>
please remove the .idea folder above and update the gitignore so this doesn't keep happening

2023-07-19 14:26 UTC, shaunganley commented on pom.xml
> +    <artifactId>TeamTwo</artifactId>
```suggestion
    <artifactId>TeamToo</artifactId>
```

2023-07-19 14:26 UTC, shaunganley commented on src/main/java/org/kainos/ea/controller/JobRoleController.java
> +        jobRoleService = new JobRoleService(new JobRoleDao(), databaseConnector);
```suggestion
        jobRoleService = new JobRoleService(new JobRoleDao(), new DatabaseConnector());
```

2023-07-19 14:26 UTC, shaunganley commented on src/main/java/org/kainos/ea/controller/JobRoleController.java
> +        } catch (FailedToGetJobRolesException | SQLException e) {
catch the SQLException in the service and throw a FailedToGetJobRolesException instead

2023-07-19 14:26 UTC, shaunganley commented on src/main/java/org/kainos/ea/dao/JobRoleDao.java
> +        ResultSet rs = st.executeQuery("SELECT * FROM `JobRole`;");
only select the columns you need

2023-07-19 14:26 UTC, shaunganley commented on src/main/java/org/kainos/ea/model/JobRole.java
> +        CapabilityID = capabilityID;
make these consistent with the lines above

2023-07-19 14:26 UTC, shaunganley commented on src/main/java/org/kainos/ea/service/JobRoleService.java
> +        return jobRoleDao.getAllJobRoles(databaseConnector.getConnection());
FailedToGetJobRolesException isn't thrown from the DAO, catch the SQLException here and throw the FailedToGetJobRolesException

2023-07-19 14:26 UTC, shaunganley commented on src/main/java/org/kainos/ea/util/DatabaseConnector.java
> +    public Connection getConnection() throws SQLException {
why remove static?

2023-07-19 14:26 UTC, shaunganley commented on src/test/java/org/kainos/ea/integration/JobRoleIntegrationTest.java
> +        List<JobRole> response = APP.client().target("http://localhost:8080/api/job_roles")
don't hardcode 'http://localhost:8080' instead pass it in as an environment variable so you can set it to the AWS URL in the future

2023-07-19 14:26 UTC, shaunganley commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
> +        List<JobRole> expected_result = new ArrayList<>();
you don't use snake case anywhere else, make consistent

2023-07-19 14:26 UTC, shaunganley commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
> +    void getJobRoles_shouldThrowSQLException_whenDaoThrowsSQLException() throws SQLException {
update this test to throw custom exception

2023-07-19 14:26 UTC, shaunganley commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
> +    @Test
add a unit test for the databaseConnector.getConnection() method throwing an exception

2023-07-19 14:56 UTC, kamil-biegaj reviewed
Checked over half of the changes, not sure if the other half has been fixed yet.

2023-07-19 15:40 UTC, kamil-biegaj submitted a review, later dismissed

2023-07-19 15:40 UTC, kamil-biegaj commented on src/main/java/org/kainos/ea/controller/JobRoleController.java
> +            return Response.serverError().build();
Maybe use another exception for this such as: Response.status(Response.Status.NOT_FOUND).build();

2023-07-20 10:05 UTC, shaunganley reviewed
getting close. please add unit tests for the controller class and address the other comments

2023-07-20 10:05 UTC, shaunganley commented on .gitignore
> +.idea/stat.log
```suggestion
.idea/
```

2023-07-20 10:05 UTC, shaunganley commented on .github/workflows/maven.yml
> +  DB_HOST: ${{ secrets.DB_HOST }}
move these under the job that needs them as they won't be required if other steps are added

2023-07-20 10:05 UTC, shaunganley commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
> +        List<JobRole> expected_result = new ArrayList<>();
this is still an issue

2023-07-20 10:05 UTC, shaunganley commented on src/test/java/org/kainos/ea/service/JobRoleServiceTest.java
> +    @Test
this still needs added

2023-07-20 12:39 UTC, shaunganley reviewed
great stuff, can you add some controller unit tests then this PR is good to go

2023-07-20 12:39 UTC, shaunganley commented on src/test/java/org/kainos/ea/integration/JobRoleIntegrationTest.java
> +        String url = System.getenv("DB_URL") + "/api/job_roles";
I don't think this is named correctly, is this an API_URL?

2023-07-21 12:28 UTC, philipwilson5 reviewed
looks good

2023-07-21 12:50 UTC, shaunganley approved these changes
great work

2023-07-21 14:01 UTC, philipwilson5 reviewed
all good

2023-07-21 15:26 UTC, philipwilson5 approved these changes

2023-07-24 08:00 UTC, ConnMeehan approved these changes

2023-07-24 08:00 UTC, merged

2023-07-24 08:10 UTC, AlexMcC02 commented
Test