Us002 view job specification
AlexMcC02/TeamTwo-BackEnd pull request #5
Opened 2023-07-20 09:04 UTC by kamil-biegaj

2023-07-20 11:01 UTC, philipwilson5 reviewed
Same issues as in us002

2023-07-28 08:33 UTC, shaunganley requested changes
good start. missing controller unit tests and looks like there's some files copied across that shouldn't be in here

2023-07-28 08:33 UTC, shaunganley commented on .gitignore
> +.idea/stat.log
you should .gitignore the entire .idea directory rather than the files

2023-07-28 08:33 UTC, shaunganley commented on pom.xml
> +
surely these already exist on main, can you make sure your branch is up to date with latest main?

2023-07-28 08:33 UTC, shaunganley commented on src/java/com/example/api/perf/test/integrationTests/StudentControllerMockTests.java
> +
what is this file?

2023-07-28 08:33 UTC, shaunganley commented on src/java/com/example/api/perf/test/integrationTests/StudentControllerMockmvcTests.java
> +public class StudentControllerMockmvcTests {
what is this file?

2023-07-28 08:33 UTC, shaunganley commented on src/java/com/example/api/perf/test/integrationTests/StudentControllerTests.java
> +public class StudentControllerTests {
what is this file?

2023-07-28 08:33 UTC, shaunganley commented on src/main/java/org/kainos/ea/controller/JobRoleController.java
> +        }
there should be another exception scenario for the ID not existing in the DB which should return a 404

2023-07-28 08:33 UTC, shaunganley commented on src/main/java/org/kainos/ea/service/JobRoleService.java
> +            return Spec;
you shouldn't use the same exception for JobRoleDoesNotExist as the SQLException below as these should return 2 different error codes from the API

2023-07-28 08:33 UTC, shaunganley commented on src/main/java/org/kainos/ea/service/JobRoleService.java
> +            throw new RuntimeException(e);
don't throw generic exceptions, you can throw DatabaseConnectionException from this method and catch it in the controller

2023-07-28 08:33 UTC, shaunganley commented on src/test/java/com/example/api/perf/test/integrationTests/JobRoleIntegrationTest.java
> +        assertEquals(404, response.getStatus());
firstly, these should be separate tests in better names test methods. secondly, this test won't pass as you never return 404 from your endpoint

2023-07-28 08:33 UTC, shaunganley commented on src/test/java/com/example/api/perf/test/integrationTests/JobRoleIntegrationTest.java
> +        assertNotNull(response.getEntity());
can you also assert that the ID of the spec returned is the same as the one you request in the URL

2023-07-28 08:33 UTC, shaunganley commented on src/test/java/com/example/api/perf/test/integrationTests/JobRoleServiceTest.java
> +
```suggestion

```

2023-07-28 08:33 UTC, shaunganley commented on src/test/java/com/example/api/perf/test/integrationTests/JobRoleServiceTest.java
> +}
you don't performance test in your unit tests, please remove

2023-07-28 08:33 UTC, shaunganley commented on src/test/java/com/example/api/perf/test/integrationTests/JobRoleServiceTest.java
> +        Mockito.when(jobRoleDao.getSpecificationById(id, databaseConnector.getConnection())).thenThrow(new SQLException("Database connection error"));
```suggestion
        Mockito.when(jobRoleDao.getSpecificationById(id, databaseConnector.getConnection())).thenThrow(SQLException.class));
```

2023-07-28 08:33 UTC, shaunganley commented on src/test/java/com/example/api/perf/test/integrationTests/JobRoleIntegrationTest.java
> +package com.example.api.perf.test.integrationTests;
this shouldn't be in a perf test directory

2023-07-28 08:33 UTC, shaunganley commented on src/test/java/com/example/api/perf/test/integrationTests/JobRoleServiceTest.java
> +package com.example.api.perf.test.integrationTests;
this shouldn't be in a perf test directory

2023-07-31 08:38 UTC, kamil-biegaj commented
@ccurran01

2023-07-31 13:28 UTC, AlexMcC02 approved these changes
Looks good!

2023-07-31 13:49 UTC, ccurran01 approved these changes

2023-07-31 13:51 UTC, merged