Us003 view capability
AlexMcC02/TeamTwo-BackEnd pull request #6
Opened 2023-07-20 10:20 UTC by ConnMeehan

2023-07-20 11:03 UTC, philipwilson5 reviewed
Build failing

2023-07-25 13:21 UTC, AlexMcC02 approved these changes
Looks good to me.

2023-07-26 08:07 UTC, philipwilson5 approved these changes
Looks good!

2023-07-26 08:37 UTC, shaunganley requested changes
seems to have been some misunderstanding with what was required for this ticket. rather than creating a new endpoint, update the existing endpoint to return the capability

2023-07-26 08:37 UTC, shaunganley commented on .github/workflows/maven.yml
> +        run: mvn -B package --file pom.xml
these indent changes have broken the tests running, please revert

2023-07-26 08:37 UTC, shaunganley commented on src/main/java/org/kainos/ea/controller/JobRoleController.java
> +    }
you don't need a new endpoint, you can just return the capability as part of the existing get roles endpoint for US001

2023-07-26 08:37 UTC, shaunganley commented on src/main/java/org/kainos/ea/dao/JobRoleDao.java
> +}
this isn't needed, update the existing query to return the capability

2023-07-26 08:37 UTC, shaunganley commented on src/main/java/org/kainos/ea/exception/FailedToGetCapabilityException.java
> +}
not needed

2023-07-26 08:37 UTC, shaunganley commented on src/main/java/org/kainos/ea/model/Capability.java
> +}
not needed

2023-07-26 08:37 UTC, shaunganley commented on src/main/java/org/kainos/ea/service/JobRoleService.java
> +}
not needed

2023-07-26 12:35 UTC, shaunganley reviewed
looks good, can you update an integration test to check that the capability is being returned and is not null?

2023-07-27 09:53 UTC, shaunganley approved these changes

2023-08-01 08:53 UTC, merged